namespace :styles do
  desc "Generate the locked Rouge theme before compiling the site's CSS"
  task rouge: :environment do
    output = Rails.root.join("tmp/stylesheets/rouge.css")
    css = "/* Generated by styles:rouge using Rouge #{Rouge.version}; do not edit. */\n#{Rouge::Themes::ThankfulEyes.render}\n"
    FileUtils.mkdir_p(output.dirname)
    File.write(output, css) unless output.exist? && output.read == css
  end
end

%w[tailwindcss:build tailwindcss:watch].each do |task_name|
  Rake::Task[task_name].enhance([ "styles:rouge" ])
end

# Sprockets previously supplied precompressed files. Preserve that delivery
# behavior for plain Puma hosts as well as the supported Thruster container.
Rake::Task["assets:precompile"].enhance do
  require "zlib"

  Dir[Rails.application.config.assets.output_path.join("**/*.{css,js,svg}")].sort.each do |path|
    Zlib::GzipWriter.open("#{path}.gz", Zlib::BEST_COMPRESSION) do |gzip|
      gzip.mtime = 0
      gzip.write(File.binread(path))
    end
  end
end
